version: '3'
services:
  kanboard:
    build: .
    image: kanboard/kanboard:v1.2.3
    container_name: kanboard
    restart: unless-stopped
    volumes:
      - ./kanboard_data:/var/www/app/data
      - ./kanboard_ssl:/etc/nginx/ssl
      - ./kanboard_plugins:/var/www/app/plugins
