version: "3"

networks:
 proxy:
  external: true

services:
 kanboard:
  image: kanboard/kanboard:latest
 
  ports:
   - "8080:80"

  volumes:
   - ./kanboard_data:/var/www/app/data
   - ./kanboard_plugins:/var/www/app/plugins
   - ./kanboard_ssl:/etc/nginx/ssl

  labels:
   - traefik.backend=kanboard
   - traefik.frontend.rule=Host:kanboard.raulchiclano.es
   - traefik.http.middlewares.kanboard-https-redirect.redirectscheme.scheme=websecure
   - traefik.docker.network=web
   - traefik.port=80
   - traefik.enable=true
   - traefik.http.routers.kanboard.middlewares=webdav-https-redirect
   - traefik.http.routers.kanboard-secure.entrypoints=websecure
   - traefik.http.routers.kanboard-secure.rule=Host(`${FQDN}`)
   - traefik.http.routers.kanboard-secure.tls=true
   - traefik.http.routers.kanboard-secure.tls.certresolver=letsencrypt
 

  networks:
   - proxy
