version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: ${UID}:${GID}
    volumes:
      - ./srv:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
