version: '3'

services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    env_file:
      - gotify.env
    volumes:
      - ./data:/app/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.http.routers.gotify.entrypoints=web
      - traefik.http.routers.gotify.rule=Host(`${GOTIFY_FQDN}`)
      - traefik.http.middlewares.gotify-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.gotify.middlewares=gotify-https-redirect
      - traefik.http.routers.gotify-secure.entrypoints=websecure
      - traefik.http.routers.gotify-secure.rule=Host(`${GOTIFY_FQDN}`)
      - traefik.http.routers.gotify-secure.tls=true
      - traefik.http.routers.gotify-secure.tls.certresolver=letsencrypt
      - com.centurylinklabs.watchtower.enable="true"
      - com.centurylinklabs.watchtower.monitor-only="true"

networks:
  proxy:
    external: true
