version: "3"

services:
  ntfy:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.ntfy.loadbalancer.server.port=80
      - traefik.http.routers.ntfy.entrypoints=web
      - traefik.http.routers.ntfy.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.ntfy-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.ntfy.middlewares=ntfy-https-redirect
      - traefik.http.routers.ntfy-secure.entrypoints=websecure
      - traefik.http.routers.ntfy-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.ntfy-secure.tls=true
      - traefik.http.routers.ntfy-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
