version: '3'

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: 1000:1000
    volumes:
        - ./music:/music:ro
        - ./data:/data
