version: '3'
services:
  webdav:
    build: .
    image: atareao/webdav:v2.0
    container_name: webdav
    restart: unless-stopped
    volumes:
      - ./share:/share
      - ./htpasswd:/opt/nginx/conf/.htpasswd
